### ISSUE TITLE
How to use the restructured-text docstring style?

### ISSUE THREAD

**Issue by omri374** [mkdocstrings/mkdocstrings#237]
Hi, 
Thanks for the awesome package!

Trying to use mkdocstrings (version 0.14.0) with the `restructured-text` docstring style. 
Here's my configuration:

```
::: path.to.Class
    handler: python
    selection:
          docstring_style: restructured-text
```
Getting: `mkdocstrings.handlers.base.CollectionError: 'restructured-text'`
Also tried `docstring_style: rest` and others with no luck.

Trying to follow [this documentation](https://mkdocstrings.github.io/handlers/python/#supported-docstrings-styles), it is not clear how to make this work.

**Comment by pawamoy** [comment]
It's indeed `docstring_style: restructured-text`, and yes it's not clear in the docs, I'll mark this as "docs to improve".

```markdown
:::: path.to.Class
    handler: python
    selection:
      docstring_style: restructured-text
```

**Comment by omri374** [comment]
Hi @pawamoy, thanks for the quick response.
Still no luck. For this input (with `collections.Counter` to make sure it's not a package thing):
```
::: collections.Counter
    handler: python
    selection:
      docstring_style: google
```

Everything works.

For this input:

```
::: collections.Counter
    handler: python
    selection:
      docstring_style: resturctured-text
```

The output is:

```
ERROR   -  mkdocstrings.extension: Could not collect 'collections.Counter'
ERROR   -  Error reading page 'api.md': 'resturctured-text'
[E 210216 22:31:25 ioloop:907] Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
    Traceback (most recent call last):
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\tornado\ioloop.py", line 905, in _run
        return self.callback()
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\livereload\handlers.py", line 69, in poll_tasks
        filepath, delay = cls.watcher.examine()
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\livereload\watcher.py", line 119, in examine
        func()
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocs\commands\serve.py", line 136, in builder
        build(config, live_server=live_server, dirty=dirty)
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocs\commands\build.py", line 271, in build
        _populate_page(file.page, config, files, dirty)
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocs\commands\build.py", line 171, in _populate_page
        page.render(config, files)
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocs\structure\pages.py", line 175, in render
        self.content = md.convert(self.markdown)
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\markdown\core.py", line 264, in convert
        root = self.parser.parseDocument(self.lines).getroot()
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\markdown\blockparser.py", line 90, in parseDocument
        self.parseChunk(self.root, '\n'.join(lines))
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\markdown\blockparser.py", line 105, in parseChunk
        self.parseBlocks(parent, text.split('\n\n'))
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\markdown\blockparser.py", line 123, in parseBlocks
        if processor.run(parent, blocks) is not False:
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocstrings\extension.py", line 154, in run
        xml_element = self.process_block(identifier, block, heading_level)
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocstrings\extension.py", line 193, in process_block
        data: Any = handler.collector.collect(identifier, selection)
      File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocstrings\handlers\python.py", line 220, in collect
        raise CollectionError(error)
    mkdocstrings.handlers.base.CollectionError: 'resturctured-text'
ERROR   -  Exception in callback <bound method LiveReloadHandler.poll_tasks of <class 'livereload.handlers.LiveReloadHandler'>>
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\tornado\ioloop.py", line 905, in _run
    return self.callback()
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\livereload\handlers.py", line 69, in poll_tasks
    filepath, delay = cls.watcher.examine()
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\livereload\watcher.py", line 119, in examine
    func()
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocs\commands\serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocs\commands\build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocs\commands\build.py", line 171, in _populate_page
    page.render(config, files)
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocs\structure\pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\markdown\core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\markdown\blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\markdown\blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\markdown\blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocstrings\extension.py", line 154, in run
    xml_element = self.process_block(identifier, block, heading_level)
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocstrings\extension.py", line 193, in process_block
    data: Any = handler.collector.collect(identifier, selection)
  File "C:\Users\user\.conda\envs\my_project\lib\site-packages\mkdocstrings\handlers\python.py", line 220, in collect
    raise CollectionError(error)
mkdocstrings.handlers.base.CollectionError: 'resturctured-text'
```


**VERSIONS**
| package | version | where from |
| --- | --- | --- |
markdown      |            3.3.3              pyh9f0ad1d_0   | conda-forge
markupsafe     |          2.0.0a1                  pypi_0  |  pypi
mkdocs          |          1.1.2                      py_0  |  conda-forge
mkdocs-material         |  6.2.8                    pypi_0 |   pypi
mkdocs-material-extensions 1.0.1     |               pypi_0  |  pypi
mkdocstrings      |    0.14.0        |     pyhd8ed1ab_0 |   conda-forge

**Comment by pawamoy** [comment]
Maybe it's only in your comment, but you wrote `resturctured-text` instead of `restructured-text`. In any case, it shouldn't raise an error like this one. Could you set up a public repository on GitHub where the issue happens? I can't seem to reproduce locally.

**Comment by pawamoy** [comment]
Does the issue happen locally? Do you happen to have an old pytkdocs version installed on your system? Try deactivating and reactivating your venv, or running `hash -r` while activated. mkdocstrings spawns a pytkdocs process and I think it's using the wrong one (an old version).

**Comment by omri374** [comment]
Oh! It was indeed a typo @pawamoy. Thanks for your help! It not works. Feel free to close the ticket.

**Comment by pawamoy** [comment]
Great! Closing :slightly_smiling_face:

**Comment by omri374** [comment]
Note that docs should probably explicitly mention `restructured-text` as an option :)
