### ISSUE TITLE
show_signature_annotations doesn't seem to work

### ISSUE THREAD

**Issue by alexifm** [mkdocstrings/mkdocstrings#238]
In the signature template, I need to remove `config.show_signature_annotations` from this if I want annotations to show up:
```
{% if config.show_signature_annotations and "annotation" in parameter %}
```

I put in some print statements here:
https://github.com/mkdocstrings/mkdocstrings/blob/b4c4775e083bb55cafc038df3041f7c418836f63/src/mkdocstrings/handlers/python.py#L70-L71

``` 
print(config["show_signature_annotations"])
print(final_config["show_signature_annotations"])
```

The first print statement leads to this error:
```
Traceback (most recent call last):
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/mkdocs/commands/build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/mkdocs/commands/build.py", line 171, in _populate_page
    page.render(config, files)
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/mkdocstrings/extension.py", line 154, in run
    xml_element = self.process_block(identifier, block, heading_level)
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/mkdocstrings/extension.py", line 205, in process_block
    rendered = handler.renderer.render(data, rendering)
  File "/Users/alexifm/Projects/backend/build/client/internal/python/infima_client_internal/.nox/docs/lib/python3.8/site-packages/mkdocstrings/handlers/python.py", line 72, in render
    pprint.pprint(config["show_signature_annotations"])
  File "/Users/alexifm/.pyenv/versions/3.8.5/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/Users/alexifm/.pyenv/versions/3.8.5/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'show_signature_annotations'
```

If I remove that statement, the second one prints `False`.

- `mkdocstrings` version: 0.14.0

**Comment by alexifm** [comment]
Dumb error on my part that led to this

**Comment by pawamoy** [comment]
Glad you were able to solve it :) Thanks for coming back and closing!
