### ISSUE TITLE
Error when installing via poetry

### ISSUE THREAD

**Issue by deknowny** [mkdocstrings/mkdocstrings#262]
I have incorrect rendering of docs with material theme. 

The first bug I got when tried to run `mkdocs serve` after installing `mkdocstrings` with `poetry` in my project. I thought this was a poetry problem but it wasn't. I installed `mkdocstrings` only with pip and that seems to be ok, docs was built but it was different in some places.

This error I got when tried to install via poetry: 

```
INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/Users/an/Desktop/mkdocstrings/env/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/mkdocs/__main__.py", line 133, in serve_command
    serve.serve(
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 122, in builder
    config = load_config(
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 131, in validate
    return self.run_validation(value)
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 609, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 617, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/an/Desktop/mkdocstrings/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wheel<1.0,>=0.23.0' distribution was not found and is required by astunparse
```

 I also notice some color bugs with different version of `mkdocs-material`. For me syntax highlighting works only for version `^5` and `^6` break it.
 
 I tried to clone `mkdocstrings` and built your docs site 
 
 ```
git clone https://github.com/mkdocstrings/mkdocstrings
cd mkdocstrings
python3.8 -m venv env
source env/bin/activate
poetry install
mkdocs serve
 ```
 
 And I got the same error. May be I did something wrong

- OS: MacOS
- `mkdocstrings` version: 0.15

**Comment by deknowny** [comment]
I installed `astunparse` separately via pip and your docs built correctly

**Comment by pawamoy** [comment]
Hey @deknowny, thanks for the report!

I am able to replicate. It seems that creating a virtualenv manually (with `python3.8 -m venv env`) does not install the `wheel` package, whereas when the virtualenv is created by Poetry, there's no distribution issue. Maybe Poetry creates it differently. I think it uses `virtualenv` instead of `venv`, which automatically installs `wheel` when creating the environment.

I would suggest you rely on Poetry's ability to manage the venvs for you?
Otherwise this is easily fixed with `pip install wheel`. Then running `mkdocs serve` works correctly.

**Comment by deknowny** [comment]
Hi @pawamoy! I find an interesting issue [https://github.com/python-poetry/poetry/issues/3075](https://github.com/python-poetry/poetry/issues/3075). If I understand correctly, `wheel` moved to "default" package of `venv` and now is being ignored by Poetry. I will try updating my `venv` and poetry and repeat these steps of installing and running later.

I hope, it is the solution

**Comment by pawamoy** [comment]
That's what I was suspecting indeed. `venv` does not install `wheel` by default, while Poetry considers it a default and therefore does not install it itself, even if it's listed as a dependency (it probably considers it's already installed). @simonpercivall will also probably remove the `wheel` dependency from the `astunparse` package, so this will be fixed eventually. Closing since there's nothing actionable by mkdocstrings here! Thanks for your report :slightly_smiling_face:
