### ISSUE TITLE
bump requirements to include markupsafe>=2.0 and jinja2>=3

### ISSUE THREAD

**Issue by hkennyv** [mkdocstrings/mkdocstrings#288]
**Please open an issue on [pytkdocs](https://github.com/pawamoy/pytkdocs/issues) instead
if this is related to Python docstrings parsing or the collection of Python objects!**

**Describe the bug**
Hey there, just though I'd open an issue for anyone else who runs into the same issue as me. I was originally getting an error: 

> pkg_resources.VersionConflict: (Jinja2 3.0.0 (/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages), Requirement.parse('Jinja2<3.0,>=2.11'))

When running `pip install mkdocs mkdocstrings`, you can see (removed irrelevant output): 

```
Collecting MarkupSafe<2.0,>=1.1 (from mkdocstrings->-r requirements.txt (line 6))
.
.
.
jinja2 3.0.0 has requirement MarkupSafe>=2.0.0rc2, but you'll have markupsafe 1.1.1 which is incompatible.
mkdocstrings 0.15.0 has requirement Jinja2<3.0,>=2.11, but you'll have jinja2 3.0.0 which is incompatible.
```

I was able to fix it by upgrading pip:

```
pip install --upgrade pip
```

But I think it still makes sense to open this issue and update the dependencies for `mkdocstrings` if possible.

**To Reproduce**
Steps to reproduce the behavior (with old pip version):

1. install virtualenv `virtualenv venv`
2. activate `source venv/bin/activate`
3. ensure using older version of `pip`, `pip install pip==18.1`
4. install mkdocs, mkdocstrings, `pip install mkdocs mkdocstrings`
5. add mkdocs.yml and docs/index.md

**mkdocs.yml**

```
site_name: MkLorum
nav:
  - Home: index.md

plugins:
  - mkdocstrings
```

**docs/index.md**

```markdown
# Hello!

This is a markdown document.
```

6. try to build project, `mkdocs build` produces the following:

<details>
<summary>output</summary>
<pre>
(venv) khuynh@kmba:temp/mkdocstest $ mkdocs build
Traceback (most recent call last):
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 131, in validate
    return self.run_validation(value)
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 609, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 617, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (Jinja2 3.0.0 (/Users/khuynh/me/develop/temp/mkdocstest/venv/lib/python3.9/site-packages), Requirement.parse('Jinja2<3.0,>=2.11'))
</pre>
</details>

**Expected behavior**
Expected behavior is to not have conflicting requirements between mkdocs and mkdocstrings

**Screenshots**
N/A

**Information (please complete the following information):**
- OS: [e.g. iOS] Mac OS 11.0.1 ARM64
- Browser: [e.g. chrome, safari] N/A
- `mkdocstrings` version: [e.g. 0.10.2]  0.15.0

**Additional context**
N/A

**Comment by pawamoy** [comment]
Hey, thank you for the report, we'll push a new version that accepts Jinja2 v3 very soon :slightly_smiling_face:
