### ISSUE TITLE
Error after updating to the lastest package version.

### ISSUE THREAD

**Issue by Nimond** [mkdocstrings/mkdocstrings#316]
**Describe the bug**
Error after updating `mkdocstrings`  `0.12.2` -> `0.15.2`

**Error:** 
``` python
ERROR    -  Error reading page 'reference/bots.md': __init__() got an unexpected keyword argument 'language_prefix'
Traceback (most recent call last):
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/mkdocs/__main__.py", line 183, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/mkdocs/commands/build.py", line 284, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/mkdocs/structure/pages.py", line 174, in render
    self.content = md.convert(self.markdown)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/mkdocstrings/extension.py", line 120, in run
    html, headings = self._process_block(identifier, block, heading_level)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/mkdocstrings/extension.py", line 175, in _process_block
    handler.renderer._update_env(self.md, self._config)  # noqa: W0212 (protected member OK)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/mkdocstrings/handlers/base.py", line 244, in _update_env
    self.update_env(new_md, config)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/mkdocstrings/handlers/python.py", line 84, in update_env
    super().update_env(md, config)
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/mkdocstrings/handlers/base.py", line 232, in update_env
    self.env.filters["highlight"] = Highlighter(md).highlight
  File "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/mkdocstrings/handlers/rendering.py", line 55, in __init__
    super().__init__(**{k: v for k, v in config.items() if k in self._highlight_config_keys})
TypeError: __init__() got an unexpected keyword argument 'language_prefix'
```

**Information (please complete the following information):**
- OS: linux (5.12.14-arch1-1)
- `mkdocs` version: 1.2.2  
- `mkdocstrings` version:  0.15.2

**Comment by pawamoy** [comment]
Could you show your `mkdocs.yml` config?

**Comment by pawamoy** [comment]
What version of `pymdown-extensions` do you have?

**Comment by Nimond** [comment]
> Could you show your `mkdocs.yml` config?

```
site_name: pybotx
site_url: !!python/object/apply:os.getenv ["SITE_URL", "https://expressapp.github.io/pybotx"]
site_description: A little python library for building bots for Express

theme:
  name: 'material'

repo_name: ExpressApp/pybotx
repo_url: https://github.com/ExpressApp/pybotx
edit_uri: ''

nav:
  - Introduction: 'index.md'
  - Tutorial - User Guide:
      - First Steps: 'development/first-steps.md'
      - Sending Messages And Files: 'development/sending-data.md'
      - Handlers Collecting: 'development/collector.md'
      - Handling Errors: 'development/handling-errors.md'
      - Dependencies Injection: 'development/dependencies-injection.md'
      - Logging: 'development/logging.md'
      - Testing: 'development/tests.md'
  - API Reference:
      - Bots: 'reference/bots.md'
      - Collecting: 'reference/collecting.md'
      - Middlewares:
          - Base: 'reference/middlewares/base.md'
          - Next Step: 'reference/middlewares/ns.md'
          - Authorization: 'reference/middlewares/authorization.md'
      - Models: 'reference/models.md'
      - Clients:
          - Methods: 'reference/clients/methods.md'
          - Async Client: 'reference/clients/async-client.md'
          - Synchronous Client: 'reference/clients/sync-client.md'
      - Testing:
          Client: 'reference/testing/test-client.md'
          Message Builder: 'reference/testing/message-builder.md'
      - Exceptions: 'reference/exceptions.md'

  - Changelog: 'changelog.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite

plugins:
  - search
  - mkdocstrings
```



> What version of `pymdown-extensions` do you have? Try to upgrade it to latest (8.2).  

(7.1 -> 8.2)
After that the old error disappeared, but I have the new one:
```
ERROR    -  mkdocstrings.extension: 'Name' object has no attribute 'value'
            Traceback (most recent call last):
              File
            "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/pytkdocs/cli.py",
            line 193, in main
                output = json.dumps(process_json(line))
              File
            "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/pytkdocs/cli.py",
            line 114, in process_json
                return process_config(json.loads(json_input))
              File
            "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/pytkdocs/cli.py",
            line 91, in process_config
                obj = loader.get_object_documentation(path, members)
              File
            "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/pytkdocs/loader.py",
            line 238, in get_object_documentation
                root_object = self.get_module_documentation(leaf, members)
              File
            "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/pytkdocs/loader.py",
            line 305, in get_module_documentation
                root_object.add_child(self.get_class_documentation(child_node))
              File
            "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/pytkdocs/loader.py",
            line 344, in get_class_documentation
                attributes_data.update(get_instance_attributes(class_.__init__))
              File
            "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/pytkdocs/parsers/attributes.py",
            line 155, in get_instance_attributes
                annotation = node_to_annotation(assignment)
              File
            "/home/dnomin/.cache/pypoetry/virtualenvs/botx-4D9uk1qq-py3.9/lib/python3.9/site-packages/pytkdocs/parsers/attributes.py",
            line 19, in node_to_annotation
                return f"{node.annotation.value.id}[{node_to_annotation(node.annotation.slice.value)}]"  # type: ignore
            AttributeError: 'Name' object has no attribute 'value'
ERROR    -  Error reading page 'reference/testing/test-client.md':
ERROR    -  Could not collect 'botx.testing.testing_client.base'

Aborted with a BuildError!
```

**Comment by Nimond** [comment]
But the new error is only on my pc and don't reproduce in ci, will try to fix it myself. Updating `pymdown-extensions` to the latest help, thx)

**Comment by pawamoy** [comment]
Is it possible you upgraded mkdocstrings without upgrading its dependencies? Check pytkdocs version. If it's at latest, you can open a bug report on pytkdocs repo :slightly_smiling_face: 

Thank you for coming back and closing this issue!
