### ISSUE TITLE
Documentation generation with Django forms

### ISSUE THREAD

**Issue by BrayanMota** [mkdocstrings/mkdocstrings#359]
**I'm trying to generate the documentation for my Django forms structure, but the following error message occurs:**

```
ERROR    -  mkdocstrings.extension: 'ModelFormOptions' object has no attribute 'get_fields'
            Traceback (most recent call last):
              File "C:\Users\06813515195\Documents\AGTEC\Django\agtec-mkdocs\venv\lib\site-packages\pytkdocs\cli.py", line 205, in main
                output = json.dumps(process_json(line))
              File "C:\Users\06813515195\Documents\AGTEC\Django\agtec-mkdocs\venv\lib\site-packages\pytkdocs\cli.py", line 114, in process_json
              File "C:\Users\06813515195\Documents\AGTEC\Django\agtec-mkdocs\venv\lib\site-packages\pytkdocs\cli.py", line 91, in process_config
                obj = loader.get_object_documentation(path, members)
              File "C:\Users\06813515195\Documents\AGTEC\Django\agtec-mkdocs\venv\lib\site-packages\pytkdocs\loader.py", line 358, in get_object_documentation
                root_object = self.get_module_documentation(leaf, members)
              File "C:\Users\06813515195\Documents\AGTEC\Django\agtec-mkdocs\venv\lib\site-packages\pytkdocs\loader.py", line 426, in get_module_documentation
                root_object.add_child(self.get_class_documentation(child_node))
              File "C:\Users\06813515195\Documents\AGTEC\Django\agtec-mkdocs\venv\lib\site-packages\pytkdocs\loader.py", line 542, in get_class_documentation
                if self.detect_field_model(attr_name, direct_members, all_members):
              File "C:\Users\06813515195\Documents\AGTEC\Django\agtec-mkdocs\venv\lib\site-packages\pytkdocs\loader.py", line 577, in detect_field_model
                if remainder and not attrgetter(remainder)(all_members[first_order_attr_name]):
            AttributeError: 'ModelFormOptions' object has no attribute 'get_fields'
ERROR    -  Error reading page 'forms.md':
ERROR    -  Could not collect 'usuario.forms'
```

mkdocs.yml

```
site_name: Boilerplate Django

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: yes
            show_signature: true
            group_by_category: true
          setup_commands:
            - import django
            - import os
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "base.settings")
            - django.setup()

theme:
  name: material
  language: pt
```

forms.md

```
::: usuario.forms.UsuarioForm
```

forms.py

```
from core.forms import BaseForm

from .models import Usuario

class UsuarioForm(BaseForm):
    """ Form padrão para o model Usuario """
    class Meta:
        exclude = ['deleted', 'enabled']
        model = Usuario
```

forms.py (core)

```from django import forms
from django.forms.fields import BooleanField, DateField, DateTimeField

from .models import Base


class BaseForm(forms.ModelForm):
    """Form para ser usado no classe based views"""

    # Sobrescrevendo o Init para aplicar as regras CSS
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(BaseForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            class_attrs = ""
            class_attrs = 'form-control'
            # Verificando se o campo está configurado como obrigatório
            if self.fields[field].required:
                class_attrs = "{} {}".format(class_attrs, 'obrigatorio')
            # Verificando se o campo é Booleano
            if isinstance(self.fields[field], BooleanField) is True:
                class_attrs = "{} {}".format(class_attrs, 'checked-left')
            # Verificando se o campo é do tipo DateTime
            if isinstance(self.fields[field], DateTimeField) is True:
                class_attrs = "{} {}".format(class_attrs, 'datetimefield')
            # Verificando se o campo é do tipo Date
            if isinstance(self.fields[field], DateField) is True:
                class_attrs = "{} {}".format(class_attrs, 'datefield')
            # # Verificando se o campo é do tipo FileField
            # if isinstance(self.fields[field], FileField) is True:
            #     class_attrs = "{} {}".format(class_attrs, 'custom-file-input')
            # # Verificando se o campo é do tipo ImageField
            # if isinstance(self.fields[field], ImageField) is True:
            #     class_attrs = "{} {}".format(class_attrs, 'custom-file-input')
            # Verificando se o campo é do tipo BooleanField
            if isinstance(self.fields[field], BooleanField) is True:
                class_attrs = "{} {}".format(class_attrs, 'form-check-input')
            # Atualizando os atributos do campo para adicionar as classes
            # conforme as regras anteriores
            self.fields[field].widget.attrs.update({
                'class': class_attrs
            })

    class Meta:
        model = Base
        exclude = ['enabled', 'deleted']
```

- *mkdocstrings* version: [0.17.0]

**Comment by pawamoy** [comment]
Hello, thank you for the report!

I've been working a lot on a new data collector/extractor, and unfortunately this kind of issue (third party libraries support) will be put on hold until the new handler is released :confused: Unless people send PRs of course :smile:

**Comment by pawamoy** [comment]
See [this comment](https://github.com/mkdocstrings/mkdocstrings/issues/340#issuecomment-1031797263). This should be fixed by the new handler, which is still experimental though. Thanks again for reporting :slightly_smiling_face:
