### ISSUE TITLE
Example section fails with 'NoneType' has no attribute 'strip'

### ISSUE THREAD

**Issue by psarka** [mkdocstrings/mkdocstrings#379]
**Describe the bug**
Example section does not work

**To Reproduce**
Try to render docs for Google style docstrings with an `Example` section. Here is a small repro based on https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html#example-google:

```
(venv) paulius@xps:~/Documents/repro$ tree -I venv
.
├── docs
│   └── index.md
├── mkdocs.yml
└── repro.py

1 directory, 3 files
```

Contents of index.md:

```md
# Welcome to MkDocs

:::repro
```

Contents of mkdocs.yml:

```yml
site_name: My Docs

plugins:
  - mkdocstrings
```

Contents of `repro.py`:

```python
"""Example Google style docstrings.

This module demonstrates documentation as specified by the `Google Python
Style Guide`_. Docstrings may extend over multiple lines. Sections are created
with a section header and a colon followed by a block of indented text.

Example:
    Examples can be given using either the ``Example`` or ``Examples``
    sections. 
"""
```

**Bug**
Upon running `mkdocs server` I get a rather large stacktrace, here is a truncated output:

```
(venv) paulius@xps:~/Documents/repro$ PYTHONPATH=. mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
ERROR    -  Error reading page 'index.md': 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/home/paulius/Documents/repro/venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/paulius/Documents/repro/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)

[TRUNCATED]

  File "/home/paulius/Documents/repro/venv/lib/python3.8/site-packages/mkdocstrings_handlers/python/templates/material/_base/docstring/admonition.html", line 3, in top-level template code
    <summary>{{ section.title|convert_markdown(heading_level, html_id, strip_paragraph=True) }}</summary>
  File "/home/paulius/Documents/repro/venv/lib/python3.8/site-packages/mkdocstrings/handlers/base.py", line 219, in do_convert_markdown
    return Markup(self._md.convert(text))
  File "/home/paulius/Documents/repro/venv/lib/python3.8/site-packages/markdown/core.py", line 248, in convert
    if not source.strip():
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Information (please complete the following information):**
- OS: Ubuntu
- mkdocstrings==0.18.0
- mkdocstrings-python==0.5.2
- mkdocstrings-python-legacy==0.2.1

**Additional context**
`venv` was created with the following requirements.txt:
```
mkdocs
mkdocstrings[python] >= 0.18
mkdocs-material
```

**Comment by pawamoy** [comment]
Thanks for the report, this is fixed in Griffe 0.11.5 :slightly_smiling_face:
