### ISSUE TITLE
ModuleNotFoundError when using mkdocs-gen-files

### ISSUE THREAD

**Issue by KevinMusgrave** [mkdocstrings/mkdocstrings#395]
I'm running this on a Windows 10 computer.

Here's the mkdocs.yml file: https://github.com/KevinMusgrave/pytorch-adapt/blob/trying-mkdocs-gen-files/mkdocs.yml

Here's my conda environment:
```
# Name                    Version                   Build  Channel
ca-certificates           2021.10.26           haa95532_4
certifi                   2021.10.8        py39haa95532_2
click                     8.0.4                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
ghp-import                2.0.2                    pypi_0    pypi
importlib-metadata        4.11.2                   pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
markdown                  3.3.6                    pypi_0    pypi
markupsafe                2.1.0                    pypi_0    pypi
mergedeep                 1.3.4                    pypi_0    pypi
mkdocs                    1.2.3                    pypi_0    pypi
mkdocs-autorefs           0.3.1                    pypi_0    pypi
mkdocs-gen-files          0.3.4                    pypi_0    pypi
mkdocs-literate-nav       0.4.1                    pypi_0    pypi
mkdocs-material           8.2.3                    pypi_0    pypi
mkdocs-material-extensions 1.0.3                    pypi_0    pypi
mkdocs-section-index      0.3.3                    pypi_0    pypi
mkdocstrings              0.18.0                   pypi_0    pypi
mkdocstrings-python-legacy 0.2.2                    pypi_0    pypi
openssl                   1.1.1m               h2bbff1b_0
packaging                 21.3                     pypi_0    pypi
pip                       21.2.4           py39haa95532_0
pygments                  2.11.2                   pypi_0    pypi
pymdown-extensions        9.2                      pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
python                    3.9.7                h6244533_1
python-dateutil           2.8.2                    pypi_0    pypi
pytkdocs                  0.16.0                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyyaml-env-tag            0.1                      pypi_0    pypi
setuptools                58.0.4           py39haa95532_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.37.2               h2bbff1b_0
tzdata                    2021e                hda174b7_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  2.1.6                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py39haa95532_2
zipp                      3.7.0                    pypi_0    pypi
```

Error:
```
INFO     -  Building documentation...
INFO     -  Cleaning site directory
C:\Users\Kevin\Anaconda3\envs\pydocs\lib\site-packages\mkdocstrings\handlers\python\__init__.py:13: UserWarning: The 'python-legacy' extra of mkdocstrings will become mandatory in the next release. We have no way to detect if you already specify it, so if you do, please ignore this warning. You can globally disable it with the PYTHONWARNINGS environment variable: PYTHONWARNINGS=ignore::UserWarning:mkdocstrings.handlers.python
  warnings.warn(
ERROR    -  mkdocstrings: Importing 'pytorch_adapt' failed, possible causes are:
            - an exception happened while importing
            - an element in the path does not exist
            Traceback (most recent call last):
              File "C:\Users\Kevin\Anaconda3\envs\pydocs\lib\site-packages\pytkdocs\loader.py", line 264, in get_object_tree
                parent_module = importlib.import_module(parent_module_path)
              File "C:\Users\Kevin\Anaconda3\envs\pydocs\lib\importlib\__init__.py", line 127, in import_module
                return _bootstrap._gcd_import(name[level:], package, level)
              File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
              File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
            ModuleNotFoundError: No module named 'pytorch_adapt'

            The above exception was the direct cause of the following exception:

            Traceback (most recent call last):
              File "C:\Users\Kevin\Anaconda3\envs\pydocs\lib\site-packages\pytkdocs\cli.py", line 205, in main
                output = json.dumps(process_json(line))
              File "C:\Users\Kevin\Anaconda3\envs\pydocs\lib\site-packages\pytkdocs\cli.py", line 114, in process_json
                return process_config(json.loads(json_input))
              File "C:\Users\Kevin\Anaconda3\envs\pydocs\lib\site-packages\pytkdocs\cli.py", line 91, in process_config
                obj = loader.get_object_documentation(path, members)
              File "C:\Users\Kevin\Anaconda3\envs\pydocs\lib\site-packages\pytkdocs\loader.py", line 355, in get_object_documentation
                leaf = get_object_tree(dotted_path, self.new_path_syntax)
              File "C:\Users\Kevin\Anaconda3\envs\pydocs\lib\site-packages\pytkdocs\loader.py", line 267, in get_object_tree
                raise ImportError(
            ImportError: Importing 'pytorch_adapt' failed, possible causes are:
            - an exception happened while importing
            - an element in the path does not exist
ERROR    -  Error reading page 'reference\pytorch_adapt\index.md':
ERROR    -  Could not collect 'pytorch_adapt'

Aborted with a BuildError!
```

**Comment by pawamoy** [comment]
I don't think it has anything to do with mkdocs-gen-files. I think you're just missing your project's dependencies (they *have* to be installed for the legacy Python handler to introspect your code (or you can [mock them](https://mkdocstrings.github.io/python-legacy/usage/#mocking-libraries))), or your package cannot be found, in that case see [Finding modules](https://mkdocstrings.github.io/python-legacy/usage/#finding-modules).
