### ISSUE TITLE
Avoiding "griffe.exceptions.AliasResolutionError" when using "Automatic code reference pages" recipe

### ISSUE THREAD

**Issue by techolga** [mkdocstrings/mkdocstrings#401]
I tried to generate docs according to "Automatic code reference pages" recipe, when I faced this error:
```
ERROR    -  Error reading page 'reference/tests.md': Could not resolve decimal.Decimal
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/griffe/dataclasses.py", line 912, in resolve_target
    resolved = self.modules_collection[self.target_path]
  File "/usr/local/lib/python3.10/site-packages/griffe/mixins.py", line 19, in __getitem__
    return self.members[parts[0]][parts[1:]]  # type: ignore[attr-defined]
KeyError: 'decimal'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 187, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 174, in render
    self.content = md.convert(self.markdown)
  File "/usr/local/lib/python3.10/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/usr/local/lib/python3.10/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/usr/local/lib/python3.10/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/usr/local/lib/python3.10/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/usr/local/lib/python3.10/site-packages/mkdocstrings/extension.py", line 120, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/usr/local/lib/python3.10/site-packages/mkdocstrings/extension.py", line 196, in _process_block
    rendered = handler.renderer.render(data, rendering)
  File "/usr/local/lib/python3.10/site-packages/mkdocstrings_handlers/python/renderer.py", line 125, in render
    return template.render(
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/site-packages/mkdocstrings_handlers/python/templates/material/module.html", line 1, in top-level template code
    {% extends "_base/module.html" %}
  File "/usr/local/lib/python3.10/site-packages/mkdocstrings_handlers/python/templates/material/_base/module.html", line 2, in top-level template code
    {% if config.show_if_no_docstring or module.has_docstrings %}
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
  File "/usr/local/lib/python3.10/site-packages/griffe/dataclasses.py", line 356, in has_docstrings
    if (not member.is_alias or member.resolved) and member.has_docstring:  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/griffe/dataclasses.py", line 789, in __getattr__
    attr = getattr(self.target, name)
  File "/usr/local/lib/python3.10/site-packages/griffe/dataclasses.py", line 789, in __getattr__
    attr = getattr(self.target, name)
  File "/usr/local/lib/python3.10/site-packages/griffe/dataclasses.py", line 888, in target
    self.resolve_target()
  File "/usr/local/lib/python3.10/site-packages/griffe/dataclasses.py", line 914, in resolve_target
    raise AliasResolutionError(self.target_path) from error
griffe.exceptions.AliasResolutionError: Could not resolve decimal.Decimal
```

I´m not sure if I misconfigured something or if this is a bug, but I am able to avoid it when using  _show_if_no_docstring_ in mkdocs.yml like this:
```yml
    - mkdocstrings:
        handlers:
            python:
                rendering:
                    show_if_no_docstring: yes
```

No concrete question, but maybe its helpful for someone...
 Feel free to remove this if its just unnecessary.

**Comment by pawamoy** [comment]
Hi @techolga, thanks for the report. Do you have a public repo I could use to replicate?

**Comment by techolga** [comment]
Hi @pawamoy, I made a minimal example for you to reproduce the error.

https://github.com/techolga/mkdocstring_issue_401_example

**Comment by pawamoy** [comment]
Hi again @techolga, thanks a lot for the repository, that helped a lot! It allowed me to fix several issues :slightly_smiling_face: Will push a bugfix release in a few minutes.

**Comment by pawamoy** [comment]
0.15.1 out!
