### ISSUE TITLE
Error `Importing 'module' failed`

### ISSUE THREAD

**Issue by ni-dschiller** [mkdocstrings/mkdocstrings#431]
## Folder Structure

```
.

├── docs
│   ├── docs
│   │   ├── 3rdparty
│   │   ├── index.md
│   │   ├── indices
│   │   ├── 3rdparty-downloader.md
│   ├── mkdocs.yml
│   └── overrides
└── utils
    ├── build_cminx.sh
    ├── checkout_cminx.sh
    ├── doxygen
    │   ├── build_docs.sh
    │   └── generate_doygen_file.sh
    ├── mkdocs
    │   ├── build_docs.sh
    │   ├── data
    │   ├── install_material_mkdocs.sh
    │   ├── install_mkdocs.sh
    │   ├── install_myst.sh
    │   ├── install_pandoc.sh
    │   ├── install_plugins.sh
    │   └── readme.md
    ├── sphinx
    │   ├── build_docs.sh
    │   ├── index.rst
    │   └── setup_sphinx.sh
    └── update_cminx.sh
```

## mkdocs.yml

```
site_name: mysite

theme:
  name: material  # default: material, mkdocs, readthedocs
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    # - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.highlight
    - search.share
    # - header.autohide
  palette:  # Is overwriten by the next `palette` expressions
    primary: teal  # yellow, default: indigo
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Robot Mono
  language: en
  icon:
    logo: material/passport-biometric
  # favicon: images/favicon.png

extra:
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Deutsch
#       link: /de/
#       lang: de
#   version:
#     provider: mike
  generator: true  # Remove `Made with Material for MkDocs` if `false`

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2022

extra_javascript:
  
  # Sortable tables
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

  # MathJax
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - tags:
      tags_file: indices/tags.md
  - mkdocstrings:
      default_handler: python
      # watch:
        # - src/metrics
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")

markdown_extensions:
  
  # Metadata
  - meta
  
  # Abbreviations
  - abbr
  - pymdownx.snippets

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Annotations - Insider only currently - April 2022
  - attr_list
  - md_in_html
  - pymdownx.superfences

  # Buttons
  - attr_list

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  # Data tables
  - tables

  # Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # Grids - Insider only currently - April 2022
  - attr_list
  - md_in_html

  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  
  # MathJax
  - pymdownx.arithmatex:
      generic: true

  # Icons, Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

```

## Version
```
mkdocstrings                                      0.18.1
```

## Error Message

```
ERROR    -  mkdocstrings: Importing 'module' failed, possible causes are:
            - an exception happened while importing
            - an element in the path does not exist
            Traceback (most recent call last):
              File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pytkdocs/loader.py", line 264, in get_object_tree
                parent_module = importlib.import_module(parent_module_path)
              File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/importlib/__init__.py", line 127, in import_module
                return _bootstrap._gcd_import(name[level:], package, level)
              File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
              File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
            ModuleNotFoundError: No module named 'module'

            The above exception was the direct cause of the following exception:

            Traceback (most recent call last):
              File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pytkdocs/cli.py", line 205, in main
                output = json.dumps(process_json(line))
              File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pytkdocs/cli.py", line 114, in process_json
                return process_config(json.loads(json_input))
              File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pytkdocs/cli.py", line 91, in process_config
                obj = loader.get_object_documentation(path, members)
              File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pytkdocs/loader.py", line 355, in get_object_documentation
                leaf = get_object_tree(dotted_path, self.new_path_syntax)
              File "/Users/dirk.schiller/.pyenv/versions/3.9-dev/lib/python3.9/site-packages/pytkdocs/loader.py", line 267, in get_object_tree
                raise ImportError(
            ImportError: Importing 'module' failed, possible causes are:
            - an exception happened while importing
            - an element in the path does not exist
ERROR    -  Error reading page '3rdparty-downloader.md':
ERROR    -  Could not collect 'module'
```

## 3rdparty-downloader.md

```
# 3rdparty-downloader.cmake

::: module
3rdparty-downloader.cmake
:::


::: function
download_package(PackageName Filename Url)

param PackageName

:   name

param Filename

:   name of file

param Url

:   base url

::: note
::: title
Note
:::

the archive
```

## 3rdparty-downloader.rst

```

############################
3rdparty-downloader.cmake
############################

.. module:: 3rdparty-downloader.cmake


.. function:: download_package(PackageName Filename Url)

   :param PackageName: name
   :param Filename:    name of file
   :param Url:         base url
   
   .. note::
      the archive
```

I guess the issue here is that the `module` is coming from `CMinx` ( https://cmakepp.github.io/CMinx ) and `mdkdocstrings` is not aware of that. And `pandoc` transformed the CMinx `.rst` files to `.md`. How could I translate that for `mkdocstrings` if possible ?

**Comment by ni-dschiller** [comment]
I could fix it for now with those transform steps:

```
# Replace `:::` with `*` in all `.md` files
sed -i '.bak' 's/:::/*/g' docs/*.md
sed -i '.bak' 's/:::/*/g' docs/**/*.md
```

**Comment by pawamoy** [comment]
Hi, thanks for coming back and closing with a solution. The syntax is indeed `::: identifier`, followed by an optional, indented YAML block for configuration. Anything else will not be recognized.
