### ISSUE TITLE
build fail - import data type from src package

### ISSUE THREAD

**Issue by Brunner246** [mkdocstrings/mkdocstrings#432]
Hi

For the documentation of the classes and functions we have a src folder with subfolders containing .py files. 
When I import classes into other .py files, I get a build error.

Can anyone help me to solve this problem?

Thanks

![image](https://user-images.githubusercontent.com/71121348/168233910-904831c5-5d38-4371-9d81-a355cdb24c15.png)

- project folder structure

``` 
repo
├── docs\
│   ├── documentation\
│   │   ├── attribute_controller.md
│   │   ├── bim_controller.md
│   │   .......
│   │
│   ├── img\
│   ├── stylesheets\
|
├── src\
│   ├── attribute_controller\
│   │   │
│   │   └── __init__.py
│   │......
│   │
│   ├── cadwork\
│   │   │
│   │   └── __init__.py
│   │......
│
│
├── .readthedocs.yaml
...
├── mkdocs.yml
├── pyproject.toml
├── README.md
├── requirements.txt
...
``` 

```yml
plugins:
  - search:
      separator: '[\s\-\.\_]+'     
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
```
**mkdocstrings version**
`mkdocstrings==0.17.0`

**error**
````
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/cwapi3dpython/checkouts/41/_build/html
[31mERROR    -  [0mmkdocstrings.extension: module 'src' has no attribute 'attribute_controller'
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwapi3dpython/envs/41/lib/python3.9/site-packages/pytkdocs/cli.py", line 205, in main
    output = json.dumps(process_json(line))
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwapi3dpython/envs/41/lib/python3.9/site-packages/pytkdocs/cli.py", line 114, in process_json
    return process_config(json.loads(json_input))
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwapi3dpython/envs/41/lib/python3.9/site-packages/pytkdocs/cli.py", line 91, in process_config
    obj = loader.get_object_documentation(path, members)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwapi3dpython/envs/41/lib/python3.9/site-packages/pytkdocs/loader.py", line 355, in get_object_documentation
    leaf = get_object_tree(dotted_path, self.new_path_syntax)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cwapi3dpython/envs/41/lib/python3.9/site-packages/pytkdocs/loader.py", line 281, in get_object_tree
    obj = getattr(current_node.obj, obj_name)
AttributeError: module 'src' has no attribute 'attribute_controller'

[31mERROR    -  [0mError reading page 'documentation/attribute_controller.md':
[31mERROR    -  [0mCould not collect 'src.attribute_controller.__init__'

Aborted with a BuildError!
```

**Comment by Brunner246** [comment]
#252 solution found

**Comment by pawamoy** [comment]
Python let's you import from src directly because it implicitly thinks it's a namespace package. I would recommend not doing that, and instead make sure all packages in src are properly made available during runtime, either by actually installing them (in a venv for example) or by modifying the PYTHONPATH environment variable.
