### ISSUE TITLE
mkdocstrings: Template 'module.html' not found for 'python' handler and theme 'material'.

### ISSUE THREAD

**Issue by zillionare** [mkdocstrings/mkdocstrings#434]
**Describe the bug**
mkdocs serve -a 0.0.0.0:9000 prints the following error:

```
ERROR    -  mkdocstrings: Template 'module.html' not found for 'python' handler and theme 'material'.
ERROR    -  Error reading page 'api.md': module.html
Traceback (most recent call last):
  File "/root/miniconda3/envs/alpha/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/mkdocstrings/extension.py", line 120, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/mkdocstrings/extension.py", line 196, in _process_block
    rendered = handler.renderer.render(data, rendering)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/mkdocstrings/handlers/python/renderer.py", line 70, in render
    template = self.env.get_template(f"{data['category']}.html")
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: module.html
```

**Information (please complete the following information):**
- OS: ubuntu 20.04
- Browser: firefox
- `mkdocstrings` version: 0.18
- `mkdocs` version: 1.1.2
- `material`: 8.2.15
- autorefs: 0.4.1

**Comment by pawamoy** [comment]
Hi, can you list the contents of /root/miniconda3/envs/alpha/lib/python3.8/site-packages/mkdocstrings?

You can also try to recreate a fresh conda env.

**Comment by zillionare** [comment]
It recovered magically. I don't realize anything I did. Is it possible caused by my doc strings but the error report is incorrect?

**Comment by pawamoy** [comment]
I don't think so. Closing for now, feel free to reopen.
