### ISSUE TITLE
how to troubleshooting effeciently?

### ISSUE THREAD

**Issue by zillionare** [mkdocstrings/mkdocstrings#435]
mkdocstrings is great and it's one of facts drive me to release a cookie-cutter template that include mkdocstrings, to share this great tool with more people. However, I found (or something I don't know) it's hard to figure out the root cause when things going wrong. For example, I currently got this:

```
ERROR    -  mkdocstrings.handlers.python: Error while loading JSON:
ERROR    -  mkdocstrings.extension: Could not collect 'traderclient'
ERROR    -  Error reading page 'api.md': Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/mkdocstrings/handlers/python.py", line 210, in collect
    result = json.loads(stdout)
  File "/root/miniconda3/envs/tclient/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/root/miniconda3/envs/tclient/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/miniconda3/envs/tclient/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/tclient/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/mkdocs/__main__.py", line 187, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/mkdocs/structure/pages.py", line 174, in render
    self.content = md.convert(self.markdown)
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/mkdocstrings/extension.py", line 155, in run
    xml_element = self.process_block(identifier, str(block))
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/mkdocstrings/extension.py", line 194, in process_block
    data: Any = handler.collector.collect(identifier, selection)
  File "/root/miniconda3/envs/tclient/lib/python3.8/site-packages/mkdocstrings/handlers/python.py", line 213, in collect
    raise CollectionError(str(exception)) from exception
mkdocstrings.handlers.CollectionError: Expecting value: line 1 column 1 (char 0)
```
None of single line refers to my code/docstring, thus it's very hard to find the culprit.

Is it possible for mkdocstring to dump out what cause issues?

**Comment by pawamoy** [comment]
Hi! The legacy handler indeed makes it difficult to understand what is causing issues. Did you try to use the new Python handler instead?

**Comment by zillionare** [comment]
Thanks @pawamoy. I'll try it later. Most of time the issue is caused by application source code, say, some import issues.

**Comment by pawamoy** [comment]
I'll check again what causes pytkdocs to not output anything.

**Comment by pawamoy** [comment]
Closing for now, feel free to reopen with a reproducible example!
