### ISSUE TITLE
Documentation broken for an unknown reason.

### ISSUE THREAD

**Issue by kunguz** [mkdocstrings/mkdocstrings#438]
**Describe the bug**
The documentation is not building if I use mkdocstrings.

**To Reproduce**
1. `git clone git@github.com:kunguz/odak.git`
2.  `cd odak`
3. `mkdocs serve`

**Expected behavior**
A running mkdocs server, which was the case until a week or a two ago, I haven't changed anything in the meantime. But various updates took place to `mkdocstrings` and `mkdocs-material` in the meantime.
I can't interpret the issue from the terminal output.
If I remove `mkdocstrings` related lines from my `MD` files, things works. If I revert to an older version of `mkdocstrings` things also work.
Everything runs perfectly if I revert to an old version, specifically `mkdocs-material==8.1.0` and `mkdocstrings==0.17.0` with `pytkdocs[numpy-style]` support.

**Information**
- Ubuntu 22.04 LTS
- Browser: Firefox 101.0 (64-bit)
- `mkdocstrings[python]` version: `0.19.0`
- `mkdocs` version: `1.3.0`

**Additional context**
```shell
$  mkdocs serve > output.txt
INFO     -  Building documentation...
INFO     -  Cleaning site directory
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - notes/holographic_light_transport.md
  - notes/optimizing_holograms_using_odak.md
  - notes/using_metameric_loss.md
  - odak/beginning.md
  - odak/installation.md
  - odak/learn/perception/blur_loss.md
  - odak/learn/perception/make_3d_location_map.md
  - odak/learn/perception/make_eccentricity_distance_maps.md
  - odak/learn/perception/make_pooling_size_map_lod.md
  - odak/learn/perception/make_pooling_size_map_pixels.md
  - odak/learn/perception/make_radial_map.md
  - odak/learn/perception/metamer_mse_loss.md
  - odak/learn/perception/metameric_loss.md
  - odak/learn/perception/metameric_loss_uniform.md
  - odak/learn/perception/radially_varying_blur.md
  - odak/learn/perception/rgb_2_ycrcb.md
  - odak/learn/perception/spatial_steerable_pyramid.md
  - odak/learn/perception/ycrcb_2_rgb.md
  - odak/learn/wave/adjust_phase_only_slm_range.md
  - odak/learn/wave/band_limited_angular_spectrum.md
  - odak/learn/wave/calculate_amplitude.md
  - odak/learn/wave/calculate_phase.md
  - odak/learn/wave/custom.md
  - odak/learn/wave/generate_complex_field.md
  - odak/learn/wave/gerchberg_saxton.md
  - odak/learn/wave/gradient_descent.md
  - odak/learn/wave/impulse_response_fresnel.md
  - odak/learn/wave/linear_grating.md
  - odak/learn/wave/phase_gradient.md
  - odak/learn/wave/point_wise.md
  - odak/learn/wave/prism_phase_function.md
  - odak/learn/wave/produce_phase_only_slm_pattern.md
  - odak/learn/wave/propagate_beam.md
  - odak/learn/wave/quadratic_phase_function.md
  - odak/learn/wave/set_amplitude.md
  - odak/learn/wave/shift_w_double_phase.md
  - odak/learn/wave/speckle_contrast.md
  - odak/learn/wave/stochastic_gradient_descent.md
  - odak/learn/wave/transfer_function_kernel.md
  - odak/learn/wave/wavenumber.md
  - odak/tools/check_directory.md
  - odak/tools/convert_bytes.md
  - odak/tools/list_files.md
  - odak/tools/load_dictionary.md
  - odak/tools/load_image.md
  - odak/tools/resize_image.md
  - odak/tools/save_dictionary.md
  - odak/tools/save_image.md
  - odak/tools/shell_command.md
  - odak/tools/size_of_a_file.md
  - odak/wave/adaptive_sampling_angular_spectrum.md
  - odak/wave/add_phase.md
  - odak/wave/add_random_phase.md
  - odak/wave/adjust_phase_only_slm_range.md
  - odak/wave/angular_spectrum.md
  - odak/wave/band_extended_angular_spectrum.md
  - odak/wave/band_limited_angular_spectrum.md
  - odak/wave/calculate_amplitude.md
  - odak/wave/calculate_intensity.md
  - odak/wave/calculate_phase.md
  - odak/wave/double_convergence.md
  - odak/wave/electric_field_per_plane_wave.md
  - odak/wave/fraunhofer.md
  - odak/wave/fraunhofer_equal_size_adjust.md
  - odak/wave/fraunhofer_inverse.md
  - odak/wave/generate_complex_field.md
  - odak/wave/gerchberg_saxton.md
  - odak/wave/gerchberg_saxton_3d.md
  - odak/wave/impulse_response_fresnel.md
  - odak/wave/linear_grating.md
  - odak/wave/prism_phase_function.md
  - odak/wave/produce_phase_only_slm_pattern.md
  - odak/wave/propagate_beam.md
  - odak/wave/propagate_field.md
  - odak/wave/propagate_plane_waves.md
  - odak/wave/quadratic_phase_function.md
  - odak/wave/rayleigh_resolution.md
  - odak/wave/rayleigh_sommerfeld.md
  - odak/wave/rotationspeed.md
  - odak/wave/set_amplitude.md
  - odak/wave/transfer_function_kernel.md
  - odak/wave/wavenumber.md
ERROR    -  Error reading page 'odak/learn/perception/blur_loss.md': '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/kaan/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/usr/lib/python3/dist-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/usr/lib/python3/dist-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/usr/lib/python3/dist-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocstrings/extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocstrings/extension.py", line 195, in _process_block
    data: CollectorItem = handler.collect(identifier, options)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocstrings_handlers/python/handler.py", line 195, in collect
    unresolved, iterations = loader.resolve_aliases(only_exported=True, only_known_modules=True)
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/loader.py", line 179, in resolve_aliases
    self.expand_wildcards(wildcards_module)
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/loader.py", line 254, in expand_wildcards
    self.expand_wildcards(member, only_known_modules, seen)  # type: ignore[arg-type]
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/loader.py", line 260, in expand_wildcards
    if new_member.name not in obj.members or obj[new_member.name].lineno < alias_lineno:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by pawamoy** [comment]
What changed is that previously you were using the *legacy* Python handler, and now you are using the *new* handler. More info here: https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers

This issue was reported in the Griffe repo as well, I'm working on a fix :slightly_smiling_face:

**Comment by kunguz** [comment]
Thank you for your fast response! Is it then because this new handler treats comments differently or needs a different kind of comment type in order to function properly? Just trying to understand the case a little bit better.

**Comment by pawamoy** [comment]
Well, the new handler works very differently compared to the legacy one. The legacy one always introspected code (import + looking at objects in memory), while the new one parses the code with the `ast` module and visits the nodes, without executing anything. The bug here was hiding in the logic of wildcard expansion, when a member with the same name as a submodule is imported.

**Comment by kunguz** [comment]
Is there anything I can do to make my code more compatible with this new handler? Or is the best course of action to wait for a fix from your side?

**Comment by pawamoy** [comment]
Already fixed :joy: Going to push a release now :slightly_smiling_face:

**Comment by kunguz** [comment]
Wow that escalated quickly :D

**Comment by pawamoy** [comment]
0.20.0 available on PyPI :smile: 
If you didn't set upper bounds on Griffe, you can just restart your pipeline and it should work :slightly_smiling_face: 
Let me know if you still encounter errors! Closing.

**Comment by kunguz** [comment]
I will give it a try now :D Thank you!

**Comment by kunguz** [comment]
```shell
pip3 install mkdocstrings[python]==0.20.0
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement mkdocstrings[python]==0.20.0 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.12.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.14.0b1, 0.14.0, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.18.0, 0.18.1, 0.19.0)
ERROR: No matching distribution found for mkdocstrings[python]==0.20.0
```

**Comment by pawamoy** [comment]
Yeah there are some delays here and there. Just try again, it'll catch up eventually :slightly_smiling_face: 
https://pypi.org/project/griffe/

**Comment by kunguz** [comment]
I am now at the new version griffe `0.2.0` and upgrade mkdocstrings to `0.19.0` and using `mkdocs-material` at `8.3.0` version.

```shell
$  mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
              - notes/holographic_light_transport.md
              - notes/optimizing_holograms_using_odak.md
              - notes/using_metameric_loss.md
              - odak/beginning.md
              - odak/installation.md
              - odak/learn/perception/blur_loss.md
              - odak/learn/perception/make_3d_location_map.md
              - odak/learn/perception/make_eccentricity_distance_maps.md
              - odak/learn/perception/make_pooling_size_map_lod.md
              - odak/learn/perception/make_pooling_size_map_pixels.md
              - odak/learn/perception/make_radial_map.md
              - odak/learn/perception/metamer_mse_loss.md
              - odak/learn/perception/metameric_loss.md
              - odak/learn/perception/metameric_loss_uniform.md
              - odak/learn/perception/radially_varying_blur.md
              - odak/learn/perception/rgb_2_ycrcb.md
              - odak/learn/perception/spatial_steerable_pyramid.md
              - odak/learn/perception/ycrcb_2_rgb.md
              - odak/learn/wave/adjust_phase_only_slm_range.md
              - odak/learn/wave/band_limited_angular_spectrum.md
              - odak/learn/wave/calculate_amplitude.md
              - odak/learn/wave/calculate_phase.md
              - odak/learn/wave/custom.md
              - odak/learn/wave/generate_complex_field.md
              - odak/learn/wave/gerchberg_saxton.md
              - odak/learn/wave/gradient_descent.md
              - odak/learn/wave/impulse_response_fresnel.md
              - odak/learn/wave/linear_grating.md
              - odak/learn/wave/phase_gradient.md
              - odak/learn/wave/point_wise.md
              - odak/learn/wave/prism_phase_function.md
              - odak/learn/wave/produce_phase_only_slm_pattern.md
              - odak/learn/wave/propagate_beam.md
              - odak/learn/wave/quadratic_phase_function.md
              - odak/learn/wave/set_amplitude.md
              - odak/learn/wave/shift_w_double_phase.md
              - odak/learn/wave/speckle_contrast.md
              - odak/learn/wave/stochastic_gradient_descent.md
              - odak/learn/wave/transfer_function_kernel.md
              - odak/learn/wave/wavenumber.md
              - odak/tools/check_directory.md
              - odak/tools/convert_bytes.md
              - odak/tools/list_files.md
              - odak/tools/load_dictionary.md
              - odak/tools/load_image.md
              - odak/tools/resize_image.md
              - odak/tools/save_dictionary.md
              - odak/tools/save_image.md
              - odak/tools/shell_command.md
              - odak/tools/size_of_a_file.md
              - odak/wave/adaptive_sampling_angular_spectrum.md
              - odak/wave/add_phase.md
              - odak/wave/add_random_phase.md
              - odak/wave/adjust_phase_only_slm_range.md
              - odak/wave/angular_spectrum.md
              - odak/wave/band_extended_angular_spectrum.md
              - odak/wave/band_limited_angular_spectrum.md
              - odak/wave/calculate_amplitude.md
              - odak/wave/calculate_intensity.md
              - odak/wave/calculate_phase.md
              - odak/wave/double_convergence.md
              - odak/wave/electric_field_per_plane_wave.md
              - odak/wave/fraunhofer.md
              - odak/wave/fraunhofer_equal_size_adjust.md
              - odak/wave/fraunhofer_inverse.md
              - odak/wave/generate_complex_field.md
              - odak/wave/gerchberg_saxton.md
              - odak/wave/gerchberg_saxton_3d.md
              - odak/wave/impulse_response_fresnel.md
              - odak/wave/linear_grating.md
              - odak/wave/prism_phase_function.md
              - odak/wave/produce_phase_only_slm_pattern.md
              - odak/wave/propagate_beam.md
              - odak/wave/propagate_field.md
              - odak/wave/propagate_plane_waves.md
              - odak/wave/quadratic_phase_function.md
              - odak/wave/rayleigh_resolution.md
              - odak/wave/rayleigh_sommerfeld.md
              - odak/wave/rotationspeed.md
              - odak/wave/set_amplitude.md
              - odak/wave/transfer_function_kernel.md
              - odak/wave/wavenumber.md
ERROR    -  Error reading page 'odak/learn/perception/blur_loss.md': Cyclic aliases detected:
              odak.learn.perception.spatial_steerable_pyramid.get_steerable_pyramid_filters
              odak.learn.perception.spatial_steerable_pyramid.get_steerable_pyramid_filters
Traceback (most recent call last):
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/dataclasses.py", line 811, in __getattr__
    attr = getattr(self.target, name)
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/dataclasses.py", line 920, in target
    self.resolve_target()
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/dataclasses.py", line 948, in resolve_target
    raise CyclicAliasError([self.target_path])
griffe.exceptions.CyclicAliasError: Cyclic aliases detected:
  odak.learn.perception.spatial_steerable_pyramid.get_steerable_pyramid_filters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaan/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/usr/lib/python3/dist-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/usr/lib/python3/dist-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/usr/lib/python3/dist-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocstrings/extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocstrings/extension.py", line 195, in _process_block
    data: CollectorItem = handler.collect(identifier, options)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocstrings_handlers/python/handler.py", line 195, in collect
    unresolved, iterations = loader.resolve_aliases(only_exported=True, only_known_modules=True)
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/loader.py", line 179, in resolve_aliases
    self.expand_wildcards(wildcards_module)
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/loader.py", line 254, in expand_wildcards
    self.expand_wildcards(member, only_known_modules, seen)  # type: ignore[arg-type]
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/loader.py", line 254, in expand_wildcards
    self.expand_wildcards(member, only_known_modules, seen)  # type: ignore[arg-type]
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/loader.py", line 267, in expand_wildcards
    obj[new_member.name] = Alias(
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/mixins.py", line 79, in __setitem__
    value.parent = self
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/dataclasses.py", line 888, in parent
    self._target.aliases[self.path] = self  # type: ignore[union-attr]  # we just checked the target is not None
  File "/home/kaan/.local/lib/python3.10/site-packages/griffe/dataclasses.py", line 813, in __getattr__
    raise CyclicAliasError([self.target_path] + error.chain)
griffe.exceptions.CyclicAliasError: Cyclic aliases detected:
  odak.learn.perception.spatial_steerable_pyramid.get_steerable_pyramid_filters
  odak.learn.perception.spatial_steerable_pyramid.get_steerable_pyramid_filters
```

**Comment by kunguz** [comment]
I think this is my bad, I am doing something stupid with the imports.

**Comment by kunguz** [comment]
Ok, this run helped me to find out some cyclic imports, which I have removed from my repository. But I am still left with this error

```shell
$  mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
INFO     -  The following pages exist in the docs directory, but are not included in the "nav"
            configuration:
              - notes/holographic_light_transport.md
              - notes/optimizing_holograms_using_odak.md
              - notes/using_metameric_loss.md
              - odak/beginning.md
              - odak/installation.md
              - odak/learn/perception/blur_loss.md
              - odak/learn/perception/make_3d_location_map.md
              - odak/learn/perception/make_eccentricity_distance_maps.md
              - odak/learn/perception/make_pooling_size_map_lod.md
              - odak/learn/perception/make_pooling_size_map_pixels.md
              - odak/learn/perception/make_radial_map.md
              - odak/learn/perception/metamer_mse_loss.md
              - odak/learn/perception/metameric_loss.md
              - odak/learn/perception/metameric_loss_uniform.md
              - odak/learn/perception/radially_varying_blur.md
              - odak/learn/perception/rgb_2_ycrcb.md
              - odak/learn/perception/spatial_steerable_pyramid.md
              - odak/learn/perception/ycrcb_2_rgb.md
              - odak/learn/wave/adjust_phase_only_slm_range.md
              - odak/learn/wave/band_limited_angular_spectrum.md
              - odak/learn/wave/calculate_amplitude.md
              - odak/learn/wave/calculate_phase.md
              - odak/learn/wave/custom.md
              - odak/learn/wave/generate_complex_field.md
              - odak/learn/wave/gerchberg_saxton.md
              - odak/learn/wave/gradient_descent.md
              - odak/learn/wave/impulse_response_fresnel.md
              - odak/learn/wave/linear_grating.md
              - odak/learn/wave/phase_gradient.md
              - odak/learn/wave/point_wise.md
              - odak/learn/wave/prism_phase_function.md
              - odak/learn/wave/produce_phase_only_slm_pattern.md
              - odak/learn/wave/propagate_beam.md
              - odak/learn/wave/quadratic_phase_function.md
              - odak/learn/wave/set_amplitude.md
              - odak/learn/wave/shift_w_double_phase.md
              - odak/learn/wave/speckle_contrast.md
              - odak/learn/wave/stochastic_gradient_descent.md
              - odak/learn/wave/transfer_function_kernel.md
              - odak/learn/wave/wavenumber.md
              - odak/tools/check_directory.md
              - odak/tools/convert_bytes.md
              - odak/tools/list_files.md
              - odak/tools/load_dictionary.md
              - odak/tools/load_image.md
              - odak/tools/resize_image.md
              - odak/tools/save_dictionary.md
              - odak/tools/save_image.md
              - odak/tools/shell_command.md
              - odak/tools/size_of_a_file.md
              - odak/wave/adaptive_sampling_angular_spectrum.md
              - odak/wave/add_phase.md
              - odak/wave/add_random_phase.md
              - odak/wave/adjust_phase_only_slm_range.md
              - odak/wave/angular_spectrum.md
              - odak/wave/band_extended_angular_spectrum.md
              - odak/wave/band_limited_angular_spectrum.md
              - odak/wave/calculate_amplitude.md
              - odak/wave/calculate_intensity.md
              - odak/wave/calculate_phase.md
              - odak/wave/double_convergence.md
              - odak/wave/electric_field_per_plane_wave.md
              - odak/wave/fraunhofer.md
              - odak/wave/fraunhofer_equal_size_adjust.md
              - odak/wave/fraunhofer_inverse.md
              - odak/wave/generate_complex_field.md
              - odak/wave/gerchberg_saxton.md
              - odak/wave/gerchberg_saxton_3d.md
              - odak/wave/impulse_response_fresnel.md
              - odak/wave/linear_grating.md
              - odak/wave/prism_phase_function.md
              - odak/wave/produce_phase_only_slm_pattern.md
              - odak/wave/propagate_beam.md
              - odak/wave/propagate_field.md
              - odak/wave/propagate_plane_waves.md
              - odak/wave/quadratic_phase_function.md
              - odak/wave/rayleigh_resolution.md
              - odak/wave/rayleigh_sommerfeld.md
              - odak/wave/rotationspeed.md
              - odak/wave/set_amplitude.md
              - odak/wave/transfer_function_kernel.md
              - odak/wave/wavenumber.md
ERROR    -  mkdocstrings: Template 'alias.html' not found for 'python' handler and theme 'material'.
ERROR    -  Error reading page 'odak/wave/calculate_amplitude.md': alias.html
Traceback (most recent call last):
  File "/home/kaan/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/usr/lib/python3/dist-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/usr/lib/python3/dist-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/usr/lib/python3/dist-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/usr/lib/python3/dist-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocstrings/extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocstrings/extension.py", line 209, in _process_block
    rendered = handler.render(data, options)
  File "/home/kaan/.local/lib/python3.10/site-packages/mkdocstrings_handlers/python/handler.py", line 215, in render
    template = self.env.get_template(f"{data.kind.value}.html")
  File "/home/kaan/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/kaan/.local/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/kaan/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kaan/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: alias.html
```

**Comment by pawamoy** [comment]
Yeah Griffe is not powerful enough yet to handle cyclic imports as well as Python itself. Is your repo public? I'd like to try and debug it :slightly_smiling_face:

**Comment by kunguz** [comment]
Sure, it is located here: https://github.com/kunguz/odak

**Comment by pawamoy** [comment]
Also, note that you can always go back to using the legacy handler if it works better in your case.

**Comment by kunguz** [comment]
In the repository, my `ci.yml` uses older version to avoid any trouble for now.

**Comment by pawamoy** [comment]
Thank you for testing the new handler then :smile: It helps improving it :slightly_smiling_face:

**Comment by pawamoy** [comment]
OK, it's because of wildcard imports again :sweat_smile: These bad boys are hard to handle!
It's also because of indirections in imports. Here are some changes I made to your imports to ease Griffe's pain :rofl: :

```diff
 # odak/__init__.py
-import numpy as np
-import odak.tools
-import odak.raytracing
-import odak.wave
-import odak.visualize
-import odak.jones
-import odak.catalog
-import odak.measurement
-import odak.learn
```

I suppose these imports are here to pre-load everything?

Then everywhere in your code:

```diff
-from odak import np
+import numpy as np
```

This is so much easier for Griffe to handle, because otherwise it builds several indirections in the aliases chains.
You can ease a bit of Griffe's pain by defining `__all__` lists in your modules as well, so that not everything is imported/aliased when using wildcard imports. Oh and I found unused imports in your modules as well. You could give a try to [isort](https://github.com/PyCQA/isort) (reorder imports) and [autoflake](https://github.com/PyCQA/autoflake) (remove unused imports).

None of this is your fault of course: Python allows it, it's very convenient for you and your users, and it's also very hard for Griffe to support using inference only. I need to add an option to Griffe so that users can choose to fallback to introspection in difficult cases like this. This difficult cases should also be documented in Griffe/mkdocstrings docs :smile: 

Anyway, I've added an additional guard in the Python handler, it should help without requiring you to change anything in your code.

Thanks again for sharing the repo, expect a bugfix soon :slightly_smiling_face:
