### ISSUE TITLE
error in reading file with python handler

### ISSUE THREAD

**Issue by icfly2** [mkdocstrings/mkdocstrings#442]
**Please open an issue on [pytkdocs](https://github.com/pawamoy/pytkdocs/issues) instead
if this is related to Python docstrings parsing or the collection of Python objects!**
Probably related to mkdocstrings or griffe rather than mkdocs or pytkdocs.

**Describe the bug**
In 0.19 the handler reads a .py file doc string as the heading. I'm not sure what causes this regression, as 0.18 works fine.

**To Reproduce**
Build docs with mkdocstrings[python]. Fails with traceback below. I will try and make a repo to share a reproducing example, butit looks like the file being read incorrectly is in a site package, as this is not text in my files.

**Expected behavior**
Build docs like in 0.18.1

**Screenshots**
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /friendster/docs/site
ERROR    -  Error reading page 'index.md': [Errno 36] File name too long: '# This script is used by Python\'s site module.\n# 1. Make it append our "_pdbpp_path_hack" module to sys.path:\n_pdbpp_path_hack\n# 2. Move it to the front if:\n#    1. it was actually added (via handling of the previous line) and not\n#       skipped because seen already), and\n#    2. there is not another one already at the beginning\n#       (e.g. via a virtualenv using "include-system-site-packages")\nimport sys'
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/usr/local/lib/python3.9/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/usr/local/lib/python3.9/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/usr/local/lib/python3.9/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/usr/local/lib/python3.9/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/usr/local/lib/python3.9/site-packages/mkdocstrings/extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/usr/local/lib/python3.9/site-packages/mkdocstrings/extension.py", line 195, in _process_block
    data: CollectorItem = handler.collect(identifier, options)
  File "/usr/local/lib/python3.9/site-packages/mkdocstrings_handlers/python/handler.py", line 182, in collect
    loader = GriffeLoader(
  File "/usr/local/lib/python3.9/site-packages/griffe/loader.py", line 99, in __init__
    self.finder: ModuleFinder = ModuleFinder(search_paths)
  File "/usr/local/lib/python3.9/site-packages/griffe/finder.py", line 59, in __init__
    self._extend_from_pth_files()
  File "/usr/local/lib/python3.9/site-packages/griffe/finder.py", line 238, in _extend_from_pth_files
    self._append_search_path(_handle_pth_file(item))
  File "/usr/local/lib/python3.9/site-packages/griffe/finder.py", line 291, in _handle_pth_file
    if added_dir.exists():
  File "/usr/local/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/usr/local/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
OSError: [Errno 36] File name too long: '# This script is used by Python\'s site module.\n# 1. Make it append our "_pdbpp_path_hack" module to sys.path:\n_pdbpp_path_hack\n# 2. Move it to the front if:\n#    1. it was actually added (via handling of the previous line) and not\n#       skipped because seen already), and\n#    2. there is not another one already at the beginning\n#       (e.g. via a virtualenv using "include-system-site-packages")\nimport sys'

**Information (please complete the following information):**
- OS: ubuntu 20.04
- Browser: NA
- `mkdocstrings` version: 0.19.0

**Additional context**

**Comment by pawamoy** [comment]
Thanks for the report. That looks like https://github.com/mkdocstrings/griffe/issues/84. I'll close as duplicate :slightly_smiling_face:
