### ISSUE TITLE
No module named 'mkdocstrings.handlers.python'

### ISSUE THREAD

**Issue by dazza-codes** [mkdocstrings/mkdocstrings#454]
```
ERROR    -  Error reading page 'aiomoto_fixtures.md': No module named 'mkdocstrings.handlers.python'
Traceback (most recent call last):
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/mkdocstrings/handlers/base.py", line 563, in get_handler
    module = importlib.import_module(f"mkdocstrings_handlers.{name}")
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mkdocstrings_handlers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/pytest-aiomoto/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/mkdocs/__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/mkdocs/commands/build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.render(config, files)
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/mkdocs/structure/pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/markdown/core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/markdown/blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/markdown/blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/markdown/blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/mkdocstrings/extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/mkdocstrings/extension.py", line 175, in _process_block
    handler = self._handlers.get_handler(handler_name, handler_config)
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/site-packages/mkdocstrings/handlers/base.py", line 565, in get_handler
    module = importlib.import_module(f"mkdocstrings.handlers.{name}")
  File "/opt/conda/envs/pytest-aiomoto/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mkdocstrings.handlers.python'

```

**To Reproduce**

See https://github.com/dazza-codes/pytest-aiomoto/pull/20

```
git clone https://github.com/dazza-codes/pytest-aiomoto
cd pytest-aiomoto
poetry install
make docs
```

**Information (please complete the following information):**

```yaml
mkdocs = {version = "^1.3.0", optional = true }
mkdocs-material = {version = "^8.0.0", optional = true }
mkdocstrings = {version = "^0.19.0", optional = true }
```

**Comment by dazza-codes** [comment]
It was working before the version update (from `0.16`) without an extra, but now it requires an extra for python support. It is a bit strange that python is an optional extra, since this is a python project and python package, you would expect the python package to be distributed with default support for the python language.

```toml
mkdocstrings = {version = "^0.19.0", extras = ["python"], optional = true }
```

**Comment by Riccorl** [comment]
I have the same issue.

**Comment by pawamoy** [comment]
Hello @dazza-codes, thanks for the report. The solution is indeed to explicitly depend on one of the Python handlers. It's not so strange considering MkDocs and mkdocstrings are language agnostic, and considering that there are currently two mutually exclusive Python handlers (the legacy and the new one). Closing as this is not an issue!
