### ISSUE TITLE
regression with 0.21.1: TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by ssbarnea** [mkdocstrings/mkdocstrings#549]
**Describe the bug**

It seems that the new release introduced a regression in a form of a stacktrace.

```
docs: commands[0]> mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/runner/work/ansible-lint/ansible-lint/site
Traceback (most recent call last):
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/lib/python3.9/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/lib/python3.9/site-packages/mkdocs/commands/build.py", line 311, in build
    env = config.plugins.run_event('env', env, config=config, files=files)
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/lib/python3.9/site-packages/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/lib/python3.9/site-packages/mkdocstrings/plugin.py", line 289, in on_env
    for page, identifier in collections.ChainMap(*(fut.result() for fut in self._inv_futures)).items():
  File "/home/runner/work/ansible-lint/ansible-lint/.tox/docs/lib/python3.9/site-packages/mkdocstrings/plugin.py", line 289, in <genexpr>
    for page, identifier in collections.ChainMap(*(fut.result() for fut in self._inv_futures)).items():
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: unhashable type: 'list'
```

**To Reproduce**

**Expected behavior**
No exception.

**Information (please complete the following information):**
- `mkdocstrings` version: 0.21.1

**Additional context**

Can be see on https://github.com/ansible/ansible-lint/actions/runs/4628756834/jobs/8188233810?pr=3249 which is bumping mkdocstrings version, this being the reason for the exception.

**Comment by pawamoy** [comment]
Thanks for the report. I know where this is coming from. My bad. Will push 0.21.2 in a few minutes!

**Comment by pawamoy** [comment]
Done.
