### ISSUE TITLE
Compatibility with `mkdocs-macros`

### ISSUE THREAD

**Issue by llucax** [mkdocstrings/mkdocstrings#615]
**Is your feature request related to a problem? Please describe.**
To be able to write more powerful documentation and avoid repetition, it is very useful to use the [`mkdocs-macros`](https://mkdocs-macros-plugin.readthedocs.io/en/latest/) plugin, but it seems the documentation written inside docstrings is not being processed by the macros plugin.

**Describe the solution you'd like**
It would be nice if there is a way to make mkdocstrings extract the docstrings before the macros plugin runs, so macros can be expanded also inside the documentation hosted in docstrings.

**Describe alternatives you've considered**
None really, just avoid using the macros plugin.

**Additional context**
I could show a way I'm using the macros plugin, but I guess it is irrelevant, as there are many many uses for it, like showing the current git tag, etc.

**Comment by pawamoy** [comment]
This has been discussed several times already, let me try to find the relevant discussions.

**Comment by llucax** [comment]
OK, I did search for `macros` in the issues and didn't find anything relevant, but I must confess I didn't went through the couple of issues that matched but the title was completely unrelated. :innocent:

**Comment by llucax** [comment]
Ah, sorry, I missed searching the discussions.

So, it is hard to do but possible if I understand correctly?

**Comment by pawamoy** [comment]
So cool haha! :grinning: 

What do you mean by including the import statements :thinking:?

**Comment by llucax** [comment]
Amazing, good to hear! I guess the chimera wasn't ready for public consumption, but I was too eager so I tried out, and sadly it didn't work. I had to change `env.config["plugins"]` to `env.conf["plugins"]` (are the [`mkdocs-macros` docs](https://mkdocs-macros-plugin.readthedocs.io/en/latest/pages/#batteries-included-default-objects) outdated? it seems like `env.config` holds the configuration of the plugin itself and `env.plugin` is not defined).

<details>
<summary>Chimera failing...</summary>

```
INFO    -  Building documentation...
INFO    -  [macros] - Macros arguments: {'module_name': 'docs/_scripts/macros', 'modules': [], 'render_by_default': True, 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'on_undefined': 'strict',
           'on_error_fail': True, 'verbose': False}
INFO    -  [macros] - Found local Python module 'docs/_scripts/macros' in: /home/luca/devel/sdk
INFO    -  [macros] - Found external Python module 'docs/_scripts/macros' in: /home/luca/devel/sdk
Traceback (most recent call last):
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/commands/build.py", line 277, in build
    config = config.plugins.on_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/plugins.py", line 527, in on_config
    return self.run_event('config', config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs_macros/plugin.py", line 585, in on_config
    self._load_modules()
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs_macros/plugin.py", line 458, in _load_modules
    self._load_module(module, local_module_name)
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs_macros/plugin.py", line 398, in _load_module
    module.define_env(self)
  File "/home/luca/devel/sdk/docs/_scripts/macros.py", line 46, in define_env
    python_env = env.conf["plugins"]["mkdocstrings"].get_handler("python").env
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocstrings/plugin.py", line 297, in get_handler
    return self.handlers.get_handler(handler_name)
           ^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocstrings/plugin.py", line 129, in handlers
    raise RuntimeError("The plugin hasn't been initialized with a config yet")
RuntimeError: The plugin hasn't been initialized with a config yet
```

</details>

**Comment by pawamoy** [comment]
@llucax thanks for testing! Try putting `mkdocstrings` **above/before** `macros` in mkdocs.yml.

**Comment by fralau** [comment]
@pawamoy 
> What do you mean by including the import statements 🤔? 

Sorry, I re-read the code, and there is no need, since it is only defining a filter (btw, `env.render` should also work).

But, then what would be Markdown/Jinja2 code in the page?

**Comment by llucax** [comment]
```
    convert_markdown = python_env.filters["convert_markdown"]
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'convert_markdown'
```

**Comment by llucax** [comment]
I had to fix again `config` -> `conf` (not sure what's going on with that). It seems to have advanced more, but still failing:

```
INFO    -  Building documentation...
INFO    -  [macros] - Macros arguments: {'module_name': 'docs/_scripts/macros', 'modules': [], 'render_by_default': True, 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'on_undefined': 'strict',
           'on_error_fail': True, 'verbose': False}
INFO    -  [macros] - Found local Python module 'docs/_scripts/macros' in: /home/luca/devel/sdk
INFO    -  [macros] - Found external Python module 'docs/_scripts/macros' in: /home/luca/devel/sdk
INFO    -  [macros] - Extra variables (config file): ['social', 'version']
INFO    -  [macros] - Extra filters (module): ['pretty']
INFO    -  Cleaning site directory
INFO    -  Doc file 'SUMMARY.md' contains an unrecognized relative link 'intro/', it was left as is. Did you mean 'intro/index.md'?
INFO    -  Doc file 'SUMMARY.md' contains an unrecognized relative link 'reference/', it was left as is.
ERROR   -  Error reading page 'intro/actors.md': define_env.<locals>.patched_update_env() missing 1 required positional argument: 'config'
[... click stuff ...]
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/commands/build.py", line 175, in _populate_page
    page.render(config, files)
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocs/structure/pages.py", line 271, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/markdown/core.py", line 254, in convert
    root = self.parser.parseDocument(self.lines).getroot()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/markdown/blockparser.py", line 84, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/markdown/blockparser.py", line 99, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/markdown/blockparser.py", line 117, in parseBlocks
    if processor.run(parent, blocks) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocstrings/extension.py", line 125, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocstrings/extension.py", line 216, in _process_block
    handler._update_env(self.md, self._config)
  File "/home/luca/devel/sdk/.direnv/python-3.11.5/lib/python3.11/site-packages/mkdocstrings/handlers/base.py", line 370, in _update_env
    self.update_env(new_md, config)
TypeError: define_env.<locals>.patched_update_env() missing 1 required positional argument: 'config'
```

**Comment by pawamoy** [comment]
OK I've ran some tests and this is working now :smile: 

```python
def define_env(env):
    @env.macro
    def is_it_working():
        return "WORKING"

    # get the `render` method of the macros plugin
    macros_render = env.conf["plugins"]["macros"].render
    # @fralau suggests that `env.render` would work too

    # get mkdocstrings' Python handler
    python_handler = env.conf["plugins"]["mkdocstrings"].get_handler("python")
 
    # get the `update_env` method of the Python handler
    update_env = python_handler.update_env

    # override the `update_env` method of the Python handler
    def patched_update_env(md, config):
        update_env(md, config)

        # get the `convert_markdown` filter of the env
        convert_markdown = python_handler.env.filters["convert_markdown"]

        # build a chimera made of macros+mkdocstrings
        def render_convert(markdown: str, *args, **kwargs):
            return convert_markdown(macros_render(markdown), *args, **kwargs)

        # patch the filter
        python_handler.env.filters["convert_markdown"] = render_convert
    
    # patch the method
    python_handler.update_env = patched_update_env
```

Example module docstring:

```python
"""Debugging utilities.

{{ is_it_working() }}
"""
```

...getting properly rendered to:

```
Debugging utilities.

WORKING
```

**Comment by fralau** [comment]
Ah, I think I am finally catching up. So you _are_ modifying the mkdocstrings' Python handler, and basically decorating it with `env.render()`. And you _are_ using `env.render()` in `define_env()`.

That's bold wizardry. 🫡  

When you are happy with it, maybe you want to package that into a [pluglet](https://mkdocs-macros-plugin.readthedocs.io/en/latest/pluglets/) for mkdocs-macros, so that anybody could use it? I would gladly put a reference to it in Mkdocs-Macros doc.

**Comment by pawamoy** [comment]
Sorry @fralau I wanted to try and write a better explanation of what we were trying to achieve. If you got it by looking at my final code snippet, that works too!

**Comment by pawamoy** [comment]
@fralau I'd like to refactor mkdocstrings a bit to make the patching easier (ideally refactor so that no patching is necessary), and then I'd be happy to provide a pluglet, yes!

**Comment by larsoner** [comment]
@pawamoy just chiming in that it would be great to have some way to hook into the `update_env` step -- personally I'm going to monkey-patch it so I can set `self.env.globals[...]` to a Python function that I can later call in my `attributes.html` template:

<details>
<summary>Code</summary>

```
def on_pre_build(config: MkDocsConfig) -> None:
    """Monkey patch mkdocstrings-python jinja template to have global vars."""
    import mkdocstrings_handlers.python.handler

    old_update_env = mkdocstrings_handlers.python.handler.PythonHandler.update_env

    def update_env(self, md, config: dict) -> None:
        old_update_env(self, md=md, config=config)
        self.env.globals["pipeline_steps"] = _ParseConfigSteps()

    mkdocstrings_handlers.python.handler.PythonHandler.update_env = update_env
```

</details>

At least for the suggestion:

- expose the Jinja env that mkdocstrings uses to render collected data to HTML

Would it make sense to add a mkdocstrings option for some hook to call? Or maybe better, could mkdocstrings look in the standard `hooks:` location for a specially named function like `mkdocstrings_on_update_env(handler: BaseHandler)` or similar? Then my snippet above would just become:

```
def mkdocstrings_on_update_env(handler):
    handler.env.globals["pipeline_steps"] = _ParseConfigSteps()
```

**Comment by pawamoy** [comment]
Hey @larsoner, sorry for the late answer.

> expose the Jinja env that mkdocstrings uses to render collected data to HTML

It's actually exposed: 

```python
def on_pre_build(config: MkDocsConfig) -> None:
    """Monkey patch mkdocstrings-python jinja template to have global vars."""
    python_handler = config["plugins"]["mkdocstrings"].get_handler("python")
    python_handler.env.globals["pipeline_steps"] = _ParseConfigSteps()
```

The point of patching `update_env` is to have access to the Markdown instance used to convert Markdown to HTML, which is the only way to reach docstrings :slightly_smiling_face: If you don't care about docstrings and just want to add globals to the Jinja env, you should be able to use the code right above.

**Comment by fralau** [comment]
Now that I come to think about it, I would favor the idea of a more general hook.

The solution proposed by @pawamoy works nicely for Mkdocs-Macros, but it wouldn't work as-is for modules that don't have a built-in scripting system like [mkdocs-bibtex](https://github.com/shyamd/mkdocs-bibtex/issues/246). They would have to implement the hack directly in their own module.

Would there be a general solution to that issue, especially if there was more than one plugin that required this functionality? For example in the form of a parameter for the mkdocstrings plugin, which would reference a list of rendererers that would have to be applied? 🤔 

```yaml
plugins:
- search
- mkdocstrings:
    post-processing:
      - mkdocs-macros!render
      - mkdocs-bibtex!process # made-up
 ```

**Comment by pawamoy** [comment]
It would be interesting to make this easy for mkdocstrings+macros, yes. But for other plugins, it looks like most of time their logic could be implemented as a Markdown extension rather than a MkDocs plugin. If they did that, then they would natively work within docstrings and we wouldn't need hacks or extra config, or pre/post-processing.

**Comment by llucax** [comment]
This needs updating: https://github.com/mkdocstrings/mkdocstrings/issues/615#issuecomment-1725767593

There seems to be some hidden breaking change, not sure if in `mkdocstrings` or `mkdocstrings-python`, at this point I don ´t know exactly what I did but with some combination of dependencies, I needed to pass the `md` argument to `update_env()` as a keyword argument, and with mkdocstrings-python 1.14.x it seems that doesn't work anymore. I now need to remove the `md` argument` from both `update_env()` and `patched_update_env()` completely.

See:

* https://github.com/frequenz-floss/frequenz-repo-config-python/pull/352/commits/82c1b483ad5a48c259656a6e22c76127e888d55c#diff-31f993f66611eb070760ec38fc6b62d4032c2af6a27c1faf293a8c51e3f87a2bL213-R213

**Comment by llucax** [comment]
I was confused about this being closed. Now I found out about Zensical. I guess there are no plans in the horizon to support something like macros in Zensical?

**Comment by pawamoy** [comment]
See https://github.com/zensical/backlog/issues/16 and the linked issues ☺️

**Comment by pawamoy** [comment]
Now supported in Zensical, see https://github.com/zensical/zensical/pull/634 😄
